ProniaMVC/ProniaMVC/Models/Slider.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProniaMVC.Models
{
    public class Slider
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public float DiscountPercent { get; set; }
        public string ImgUrl { get; set; }
        public int Order { get; set; }
        [NotMapped]
        public IFormFile Image { get; set; }


    }
}

ProniaMVC/ProniaMVC/ViewModels/Slider/CreateSliderVM.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProniaMVC.ViewModels
{
    public class CreateSliderVM
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public float DiscountPercent { get; set; }
        [Range(1,15)]
        public int Order { get; set; }
        [NotMapped]
        public IFormFile Image { get; set; }
    }
}

ProniaMVC/ProniaMVC/Areas/Admin/Controllers/SliderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProniaMVC.DAL;
using ProniaMVC.Models;
using ProniaMVC.ViewModels;
using ProniaMVC.ViewModels;

namespace ProniaMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class SliderController : Controller
    {
        AppDbContext _context { get; }

        public SliderController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View(_context.Sliders.ToList());
        }

        public IActionResult Delete(int id)
        {
            Slider slider = _context.Sliders.Find(id);
            if (slider is null)
            {
                return NotFound();
            }
            _context.Sliders.Remove(slider);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));

        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CreateSliderVM sliderVM)
        {
            if (!ModelState.IsValid) return View();
                while (_context.Sliders.Any(s=>s.Order==sliderVM.Order))
              {
                 sliderVM.Order++;
              }
            IFormFile file = sliderVM.Image;
            if (!file.ContentType.Contains("image/"))
            {
                ModelState.AddModelError("Image", "Yuklediyiniz fayl shekil formatinda deyil.");
                return View();
            }
            if (file.Length > 3 * 1024 * 1024 )
            {
                ModelState.AddModelError("Image", "Yuklediyiniz shekilin hecmi 3 megabayt - dan chox olmamalidir.");
                return View();
            }
            string fileName = Guid.NewGuid() + file.FileName;
            using (var stream = new FileStream("C:\\Users\\Ramal\\Desktop\\Pronia-Part2\\ProniaMVC-Part2\\ProniaMVC\\wwwroot\\assets\\images\\" + fileName , FileMode.Create))
            {
                file.CopyTo(stream);
            }
            Slider slider = new Slider
            {
                Name = sliderVM.Name,
                DiscountPercent = sliderVM.DiscountPercent,
                ImgUrl = fileName,
                Order = sliderVM.Order,
            };
            _context.Sliders.Add(slider);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Update(int? id)
        {
            if (id is null)
            {
                return BadRequest();
            }
            Slider slider = _context.Sliders.Find(id);
            if (slider is null)
            {
                return NotFound();
            }
            return View(slider);

        }

        [HttpPost]
        public IActionResult Update(int? id, Slider slider)
        {
            if (!ModelState.IsValid) return View();
            if (id is null || id != slider.Id) return BadRequest();
            Slider anotherslider = _context.Sliders.FirstOrDefault(s=>s.Order==slider.Order);
            if (anotherslider != null)
            {
                anotherslider.Order = _context.Sliders.Find(id).Order;
            }
            Slider existslider = _context.Sliders.Find(id);
            if (slider is null) return NotFound();
            existslider.Name = slider.Name;
            existslider.DiscountPercent = slider.DiscountPercent;
            existslider.ImgUrl = slider.ImgUrl;
            existslider.Order = slider.Order;
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));

        }
    }
}

ProniaMVC/ProniaMVC/Areas/Admin/Views/Slider/Create.cshtml
@{
    ViewData["Title"] = "Create";
}

@model CreateSliderVM
<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Create Slider</h4>
            <form class="forms-sample" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <label asp-for="Name">Name</label>
                    <input asp-for="Name" class="form-control">
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DiscountPercent">DiscountPercent</label>
                    <input asp-for="DiscountPercent" class="form-control">
                    <span asp-validation-for="DiscountPercent" class="text-danger"></span>
                </div><div class="form-group">
                    <label asp-for="Image">Image</label>
                    <input accept="image/*" asp-for="Image" class="form-control">
                    <span asp-validation-for="Image" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Order">Order</label>
                    <input asp-for="Order" class="form-control">
                    <span asp-validation-for="Order" class="text-danger"></span>
                </div>
                <button type="submit" class="btn btn-primary me-2">Submit</button>
                <button class="btn btn-light" asp-area="admin" asp-controller="Slider" asp-action="Index">Cancel</button>
            </form>
        </div>
    </div>
</div>

ProniaMVC/ProniaMVC/Areas/Admin/Views/Slider/Index.cshtml
@{
    ViewData["Title"] = "Index";
}


@model IEnumerable<Slider>
<div class="container">
    <div class="card mt-6">
        <div class="table-responsive">
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>DiscountPercent</th>
                        <th>Imgurl</th>
                        <th>Order</th>
                        <th>Edit</th>
                        <th>Delete</th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (Slider slider in Model)
                    {
                        <tr>
                            <td>@slider.Name</td>
                            <td>@slider.DiscountPercent</td>
                            <td>@slider.ImgUrl</td>
                            <td>@slider.Order</td>
                            <td><a type="button" class="btn btn-success" asp-area="Admin" asp-controller="Slider" asp-action="Update" asp-route-id="@slider.Id">Edit</a> </td>
                            <td><a type="button" class="btn btn-danger" asp-area="Admin" asp-controller="Slider" asp-action="Delete" asp-route-id="@slider.Id">Delete</a> </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

ProniaMVC/ProniaMVC/Areas/Admin/Views/Slider/Update.cshtml
@{
    ViewData["Title"] = "Update";
}

@model Slider
<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Update Slider</h4>
            <form class="forms-sample" method="post">
                <div class="form-group">
                    <label asp-for="Name">Name</label>
                    <input asp-for="Name" class="form-control">
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DiscountPercent">DiscountPercent</label>
                    <input asp-for="DiscountPercent" class="form-control">
                    <span asp-validation-for="DiscountPercent" class="text-danger"></span>
                </div><div class="form-group">
                    <label asp-for="Image">Image</label>
                    <input asp-for="Image" class="form-control">
                    <span asp-validation-for="Image" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Order">Order</label>
                    <input asp-for="Order" class="form-control">
                    <span asp-validation-for="Order" class="text-danger"></span>
                </div>
                <button type="submit" class="btn btn-primary me-2">Submit</button>
                <button class="btn btn-light" asp-area="admin" asp-controller="Slider" asp-action="Index">Cancel</button>
            </form>
        </div>
    </div>
</div>