ProniaMVC/ProniaMVC/Models/Brand.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace ProniaMVC.Models
{
    public class Brand
    {
        public int Id { get; set; }
        public string ImgUrl { get; set; }
        [NotMapped]
        public IFormFile Image { get; set; }
    }
}

ProniaMVC/ProniaMVC/ViewModels/Brand/CreateBrandVM.cs
namespace ProniaMVC.ViewModels
{
    public class CreateBrandVM
    {
        public IFormFile Image { get; set; }

    }
}

ProniaMVC/ProniaMVC/Areas/Admin/Controllers/BrandController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProniaMVC.DAL;
using ProniaMVC.Models;
using ProniaMVC.ViewModels;

namespace ProniaMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class BrandController : Controller
    {
        AppDbContext _context { get;}

        public BrandController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View(_context.Brands.ToList());
        }

        public IActionResult Delete(int id)
        {
            Brand brand = _context.Brands.Find(id);
            if (brand is null)
            {
                return NotFound();
            }
            _context.Brands.Remove(brand);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));

        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CreateBrandVM brandVM)
        {
            if (!ModelState.IsValid) return View();

            IFormFile file = brandVM.Image;
            if (!file.ContentType.Contains("image/"))
            {
                ModelState.AddModelError("Image", "Yuklediyiniz fayl shekil formatinda olmalidir.");
                return View();
            }
            if (file.Length> 3 * 1024 * 1024)
            {
                ModelState.AddModelError("Image", "Yuklediyiniz shekilin hecmi 3 megabayt -dan artiq olmamalidir");
                return View();
            }
            string fileName = Guid.NewGuid() + file.FileName;
            using (var stream = new FileStream("C:\\Users\\Ramal\\Desktop\\Pronia\\ProniaMVC\\ProniaMVC\\wwwroot\\assets\\images\\" + fileName , FileMode.Create))
            {
                file.CopyTo(stream);
            }
            Brand brand = new Brand
            {
                ImgUrl = fileName
            };
            _context.Brands.Add(brand);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Update(int? id)
        {
            if (id is null)
            {
                return BadRequest();
            }
            Brand brand = _context.Brands.Find(id);
            if (brand is null)
            {
                return NotFound();
            }
            return View(brand);

        }

        [HttpPost]
        public IActionResult Update(int? id, Brand brand)
        {
            if (!ModelState.IsValid) return View();
            if (id is null || id != brand.Id) return BadRequest();
            Brand existbrand = _context.Brands.Find(id);
            if (brand is null) return NotFound();
            existbrand.ImgUrl = brand.ImgUrl;
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));

        }
    }
}

ProniaMVC/ProniaMVC/Areas/Admin/Views/Brand/Create.cshtml
@{
    ViewData["Title"] = "Create";
}

@model CreateBrandVM
<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Create Brand</h4>
            <form class="forms-sample" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <label asp-for="Image">Image</label>
                    <input asp-for="Image" accept="image/*" class="form-control">
                    <span asp-validation-for="Image" class="text-danger"></span>
                </div>
                <button type="submit" class="btn btn-primary me-2">Submit</button>
                <button class="btn btn-light" asp-area="admin" asp-controller="Brand" asp-action="Index">Cancel</button>
            </form>
        </div>
    </div>

ProniaMVC/ProniaMVC/Areas/Admin/Views/Brand/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

@model IEnumerable<Brand>
<div class="container">
    <div class="card mt-6">
        <div class="table-responsive">
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Imgurl</th>
                        <th>Edit</th>
                        <th>Delete</th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (Brand brand in Model)
                    {
                        <tr>
                            <td>@brand.ImgUrl</td>
                            <td><a type="button" class="btn btn-success" asp-area="Admin" asp-controller="Brand" asp-action="Update" asp-route-id="@brand.Id">Edit</a> </td>
                            <td><a type="button" class="btn btn-danger" asp-area="Admin" asp-controller="Brand" asp-action="Delete" asp-route-id="@brand.Id">Delete</a> </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

ProniaMVC/ProniaMVC/Areas/Admin/Views/Brand/Update.cshtml
@{
    ViewData["Title"] = "Update";
}

@model Brand
<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Update Brand</h4>
            <form class="forms-sample" method="post">
                <div class="form-group">
                    <label asp-for="ImgUrl">Image</label>
                    <input asp-for="ImgUrl" class="form-control">
                    <span asp-validation-for="ImgUrl" class="text-danger"></span>
                </div>
                <button type="submit" class="btn btn-primary me-2">Submit</button>
                <button class="btn btn-light" asp-area="admin" asp-controller="Brand" asp-action="Index">Cancel</button>
            </form>
        </div>
    </div>