ProniaMVC/ProniaMVC/Models/Size.cs
namespace ProniaMVC.Models
{
    public class Size
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public ICollection<ProductSize> ProductSizes { get; set; }
    }
}

ProniaMVC/ProniaMVC/Areas/Admin/Controllers/SizeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProniaMVC.DAL;
using ProniaMVC.Models;

namespace ProniaMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class SizeController : Controller
    {
        AppDbContext _context { get; }

        public SizeController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View(_context.Sizes.ToList());
        }

        public IActionResult Delete(int id)
        {
            Size size = _context.Sizes.Find(id);
            if (size is null)
            {
                return NotFound();
            }
            _context.Sizes.Remove(size);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));

        }

        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        public IActionResult Create(Size size)
        {
            if (!ModelState.IsValid) return View();
            _context.Sizes.Add(size);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Update(int? id)
        {
            if (id is null)
            {
                return BadRequest();
            }
            Size size = _context.Sizes.Find(id);
            if (size is null)
            {
                return NotFound();
            }
            return View(size);

        }

        [HttpPost]
        public IActionResult Update(int? id, Size size)
        {
            if (!ModelState.IsValid) return View();
            if (id is null || id != size.Id) return BadRequest();
            Size existsize = _context.Sizes.Find(id);
            if (size is null) return NotFound();
            existsize.Name = size.Name;
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));

        }


    }
}

ProniaMVC/ProniaMVC/Areas/Admin/Views/Size/Create.cshtml
@{
    ViewData["Title"] = "Create";
}

@model Size
<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Add Size</h4>
            <form class="forms-sample" method="post">
                <div class="form-group">
                    <label asp-for="Name">Name</label>
                    <input asp-for="Name" class="form-control">
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <button type="submit" class="btn btn-primary me-2">Submit</button>
                <button class="btn btn-light" asp-area="Admin" asp-controller="Size" asp-action="Index">Cancel</button>
            </form>
        </div>
    </div>
</div>

ProniaMVC/ProniaMVC/Areas/Admin/Views/Size/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

@model IEnumerable<Size>
<div class="container">
    <div class="card mt-6">
        <div class="table-responsive">
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Edit</th>
                        <th>Delete</th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (Size size in Model)
                    {
                        <tr>
                            <td>@size.Name</td>
                            <td><a type="button" class="btn btn-success" asp-area="Admin" asp-controller="Size" asp-action="Update" asp-route-id="@size.Id">Edit</a> </td>
                            <td><a type="button" class="btn btn-danger" asp-area="Admin" asp-controller="Size" asp-action="Delete" asp-route-id="@size.Id">Delete</a> </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

ProniaMVC/ProniaMVC/Areas/Admin/Views/Size/Update.cshtml
@{
    ViewData["Title"] = "Update";
}

@model Size
<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Update Size</h4>
            <form class="forms-sample" method="post">
                <div class="form-group">
                    <label asp-for="Name">Name</label>
                    <input asp-for="Name" class="form-control">
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <button type="submit" class="btn btn-primary me-2">Submit</button>
                <button class="btn btn-light" asp-area="admin" asp-controller="Size" asp-action="Index">Cancel</button>
            </form>
        </div>
    </div>
</div>>